policy: "MlpPolicy"
learning_rate: 5e-5
n_steps: 4096
batch_size: 256
n_epochs: 20
gamma: 0.995
gae_lambda: 0.90
clip_range: 0.2
ent_coef: 0.005
total_episodes: 500

device: "cuda"
log_path: "logs/training_log_1.csv"
plot_path: "assets/training_plot.png"
